#########################################
#				My Makefile				#
#########################################

GCC = g++

main:
	@$(GCC) -o ouput main.cpp
	@./ouput
	@rm -rf ouput

struct_vector:
	@$(GCC) -o ouput struct_vector.cpp
	@./ouput
	@rm -rf ouput

run:
	@./ouput
	
clean:
	@rm -rf ouput